steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/backend-for-ml",
        "-f",
        "Dockerfile",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend-for-ml"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy backend-for-ml \
          --image gcr.io/$PROJECT_ID/backend-for-ml \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
