steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=Credentials-Bucket --project=careCarb --format='json' | jq -r '.payload.data' | base64 --decode > /workspace/carecarb-2ffde3f90c43.json
        gcloud secrets versions access latest --secret=User-defined --project=careCarb --format='json' | jq -r '.payload.data' | base64 --decode > /workspace/.env

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/backend-for-user-data"
      - "."
  
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/backend-for-user-data"

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy backend-for-user-data \
          --image gcr.io/$PROJECT_ID/backend-for-user-data \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated \
          --port=8080

options:
  logging: CLOUD_LOGGING_ONLY
