steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/backend-for-user-data"
      - "."
  
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/backend-for-user-data"

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy backend-for-user-data \
          --image gcr.io/$PROJECT_ID/backend-for-user-data \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated \
          --port=8080

options:
  logging: CLOUD_LOGGING_ONLY
